matrix:
  include:
    - name: "Server"
      language: csharp
      mono: none
      dotnet: 3.1.100
      dist: xenial
      sudo: required
      global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      before_install:
        - nvm install 12
        - nvm use 12
        - cd Server
      install:
        - npm install -C WebAPI/Static
        - dotnet restore
      script:
        - dotnet build
    - name: "Mobile"
      language: swift
      osx_image: xcode11.2
      before_install: cd Mobile
      script: xcodebuild -project CarWashService.xcodeproj -scheme CarWashService -destination platform\=iOS\ Simulator,OS\=13.2.2,name\=iPhone\ 11\ Pro\ Max build
